export default {
  "app.title": "TubaWinUi3 Official Website",
  "app.shortTitle": "TubaWinUi3",
  "app.version": "1.5.6",
  "app.author": "Luolan Gaga",
  "app.copyright": "© 2026 Luolan Gaga · Open source under GPL-3.0",
  "app.repository": "https://github.com/luolangaga/tubatool",
  "site.slogan": "PC hardware toolkit · Native WinUI 3",

  "nav.home": "Home",
  "nav.download": "Download",
  "nav.docs": "Docs",
  "nav.about": "About",
  "nav.theme": "Theme",
  "nav.github": "View source on GitHub",

  "docs.cat-guide": "User Guide",
  "docs.cat-tools": "Tools",
  "docs.cat-tutorials": "Tutorials",
  "docs.cat-dev": "Developer Docs",

  "home.hero.badge": "Native WinUI 3 · Free · Open Source",
  "home.hero.title": "The PC Hardware Testing Toolkit",
  "home.hero.subtitle": "82 professional tools included. Launch CPU-Z, GPU-Z, CrystalDiskMark with one click. Completely free, offline, zero data collection.",
  "home.hero.download": "Get TubaWinUi3",
  "home.hero.view-github": "View on GitHub",
  "home.hero.license": "This project is open source under GPL-3.0 and may be freely redistributed. Modified versions must remain open source and must not bundle malware.",
  "home.hero.license-link": "View statement",

  "home.features.title": "Made for PC enthusiasts",
  "home.features.subtitle": "Hardware detection, system maintenance and performance testing in one place",

  "home.section1.title": "Open source and completely free",
  "home.section1.text1": "TubaWinUi3 is a free, open source and privacy-focused PC hardware toolkit for Windows! No untrusted websites needed to handle your data.",
  "home.section1.text2": "It ships with 82 external tools and 20 built-in tools, including:",
  "home.section1.items": "CPU-Z processor details|GPU-Z GPU info|CrystalDiskMark disk benchmark|FurMark GPU stress test|AIDA64 system diagnostics",
  "home.section1.text3": "The toolkit is extensible - submit new tools right from the app!",

  "home.section2.title": "Hardware info at a glance",
  "home.section2.text1": "TubaWinUi3 queries CPU, motherboard, memory, GPU, disk and monitor data in real time via WMI on background threads - never blocking the UI.",
  "home.section2.items": "CPU model, cores/threads, frequency|GPU model, VRAM, driver version|Memory capacity, frequency, slots|Disk model, capacity, health|Monitor resolution, refresh rate",
  "home.section2.text2": "CPU-Z report overlay verification keeps the data accurate.",

  "home.section3.title": "Native WinUI 3 experience",
  "home.section3.text1": "Built with WinUI 3, embracing the Windows 11 design language natively.",
  "home.section3.items": "Mica / Acrylic backdrop materials|Light / Dark / System theme|Custom window background image|Compact mode / Turbo mode|Global search quick launch|x86 / x64 / ARM64 support|Modern responsive UI",

  "home.section4.title": "20 built-in utilities",
  "home.section4.text1": "20 built-in tools that work out of the box, covering common system maintenance scenarios.",
  "home.section4.items": "Certificate blocking - block rogue certificates|Port viewer - inspect TCP/UDP ports|Hosts editor - manage hosts mapping|Keyboard tester - detect key states|Junk cleaner - clean system cache|BSOD analyzer - parse crash dumps|More: battery report, speed test, KMS…",

  "home.tools.title": "82 external tools + 20 built-in tools, organized by category",
  "home.tools.more": "and more…",

  "home.support.title": "Support us!",
  "home.support.text1": "If you like TubaWinUi3, feel free to",
  "home.support.star": "star the repo",
  "home.support.feedback": "submit feedback",
  "home.support.contribute": "contribute code",
  "home.support.text2": "or submit new tools.",

  "home.footer.credit1": "Design inspired by",
  "home.footer.credit2": "UI controls powered by",
  "home.footer.credit-link": "WinUIonWeb",

  "download.title": "Download TubaWinUi3",
  "download.subtitle": "Free · Offline · Auto-detects your architecture",
  "download.version": "Latest version",
  "download.loading": "Loading…",
  "download.detect-arch": "Detected architecture:",
  "download.recommended": "Recommended",
  "download.portable": "Portable",
  "download.portable-desc": "Extract and run - no install, perfect for USB sticks",
  "download.setup": "Installer",
  "download.setup-desc": "Classic installer with shortcuts and Start Menu entries",
  "download.store": "Microsoft Store",
  "download.store-desc": "Install from the official Microsoft Store with auto-updates",
  "download.gitcode": "GitCode",
  "download.gitcode-badge": "CN Recommended",
  "download.github": "GitHub",
  "download.mirror": "Mirror",
  "download.cloud": "Cloud drives",
  "download.cloud-sub": "All architectures",
  "download.quark": "Quark",
  "download.baidu": "Baidu",
  "download.older-title": "Need an older version?",
  "download.gh-releases": "GitHub Releases",
  "download.gc-releases": "GitCode Releases",
  "download.sys-req": "System requirements",
  "download.sys-os": "OS",
  "download.sys-os-value": "Windows 10 1809+",
  "download.sys-arch": "Architecture",
  "download.sys-arch-value": "x86 / x64 / ARM64",
  "download.sys-runtime": "Runtime",
  "download.sys-runtime-value": "No extra runtime needed",
  "download.sys-disk": "Disk space",
  "download.sys-disk-value": "About 500 MB",
  "download.privacy": "Privacy",
  "download.privacy.items": "No user data collected|Everything stays on your device|No cookies, no tracking",

  "thanks.title": "Thank you for downloading TubaWinUi3",
  "thanks.subtitle": "Download started",
  "thanks.heading": "Thanks for using TubaWinUi3!",
  "thanks.desc": "We hope this toolkit helps you understand your PC better. If you like it, consider starring the repo on GitHub.",
  "thanks.download-started": "Download started",
  "thanks.download-started-desc": "Your browser opened the download task and the file is being transferred.",
  "thanks.type": "Type",
  "thanks.source": "Source",
  "thanks.meta-version": "Selected version",
  "thanks.meta-arch": "Selected architecture",
  "thanks.meta-type": "Download type",
  "thanks.meta-source": "Download source",
  "thanks.note-title": "Download did not start?",
  "thanks.note": "If the download did not start automatically, click the button below to retry.",
  "thanks.again": "Download again",
  "thanks.back-home": "Back to home",

  "about.title": "About TubaWinUi3",
  "about.subtitle": "A free, open source, privacy-focused PC hardware toolkit",
  "about.appearance": "Appearance",
  "about.theme": "Theme",
  "about.theme-desc": "Choose the site display mode",
  "about.use-system": "Use system setting",
  "about.light": "Light",
  "about.dark": "Dark",
  "about.nav-position": "Navigation pane position",
  "about.nav-position-desc": "Select how the navigation bar is displayed",
  "about.nav-auto": "Auto",
  "about.nav-left": "Left",
  "about.nav-top": "Top",
  "about.community": "Community & source",
  "about.repo-desc": "Star, feedback and contributions are welcome",
  "about.license": "License",
  "about.license-title": "GPL-3.0 License",
  "about.license-desc": "Open source under GPL-3.0, free to redistribute. Modified versions must remain open source and must never bundle malware.",
  "about.dmca": "DMCA / malware bundling statement",
  "about.thanks": "Special thanks",
  "about.thanks-desc": "This site is built with WinUIonWeb web WinUI controls",
  "about.winui-on-web": "WinUIonWeb - bringing WinUI to the web",
  "about.open-repo": "Open repository",

  "search.placeholder": "Search docs and site content…",
  "search.title": "Search",
  "search.results-for": "Results for",
  "search.results-count": "results",
  "search.empty-query": "Type keywords to search docs, tutorials and site content",
  "search.no-results": "No results found",
  "search.no-results-desc": "Try different keywords, e.g. CPU-Z, disk, blue screen, hardware info"
}
